In [ ]:
#varaible
a=10;
print("iam",a, "yeras old");

iam 10 yeras old


In [ ]:
a=int(input("enter the number"))
b=int(input("enter the 2 number"))
c=a+b
d=a-b
e=a*b
print(c)
print(d)
print(e)

enter the number122
enter the 2 number233
355
-111
28426


In [ ]:
#take a number from user if the salary is more than 50000 there is a10% tax print his final salary


In [ ]:
a=int(input("enter the salary"))
if (a>=50000):
  tax=0.1*a
  b=a-tax
  print("salary", b)
else:
  print("no")

enter the salary6466
no


In [ ]:
#get the salary from user if the salary is more  equal to 50000 apply 10% tatx detecutionof the salary is less than 5ok apply 5% tax if salaru is more 70k than apply 12% taxand if doesn't
exceeds 100k


In [ ]:
sal=int(input("Enter the salary :"))
if(sal<50000):
  tax=0.05*sal
  print("You taxes are :",tax)
  print("Your final salary is :",sal-tax)
elif(sal>=50000 and sal<=70000):
  tax=0.1*sal
  print("Your taxes are :",tax)
  print("Your final salary is :",sal-tax)
elif(sal>70000 and sal<100000):
  tax=0.12*sal
  print("Your taxes are :",tax)
  print("Your final salary is :",sal-tax)
elif (sal>=100000):
  print("You are promoted")
else :
   pass

Enter the salary :444444
You are promoted


In [ ]:
#for loop
n=int(input("enter n :"))
for i in range(1,11):
  print(n," X ",i,"= ",i*n)

enter n :1000
1000  X  1 =  1000
1000  X  2 =  2000
1000  X  3 =  3000
1000  X  4 =  4000
1000  X  5 =  5000
1000  X  6 =  6000
1000  X  7 =  7000
1000  X  8 =  8000
1000  X  9 =  9000
1000  X  10 =  10000


In [ ]:
#while loop
x=int(input("enter the table number"))
i=1
while i<=10:
  print(x,' X ',i,' = ',x*i)
  i=i+1


enter the table number88
88  X  1  =  88
88  X  2  =  176
88  X  3  =  264
88  X  4  =  352
88  X  5  =  440
88  X  6  =  528
88  X  7  =  616
88  X  8  =  704
88  X  9  =  792
88  X  10  =  880


In [ ]:
#create a list
l1=[77,"raju","prem","ajay",1.8]
l2=[99,9.9,'tag']
l1=l1+l2              #list concatanation

l1.insert(2,99)       #give the index value then the value to insert
l1.remove(99)         #give the value to delete
l1.pop()              #to remove the value at given index
print(l1)

[77, 'raju', 'prem', 'ajay', 1.8, 99, 9.9]


In [ ]:
l1.clear()
print(l1)

[]


In [ ]:
l2=[i*i for i in l1 if i>10]
print(l2)

[121, 169, 225, 289, 361]


In [ ]:
ll=[1,2,3,4,5]
lk=[i*i if i>3 else 'x' for i in ll]
print(lk)

['x', 'x', 'x', 16, 25]


In [ ]:
#take the salary from user if salary is less than 50k 10% tax otherwise 15% tax
n=int(input("Enter salary"))
list1=[]
list1.append(n)
list2=[n-(n*0.1) if n<50000 else n-(n*0.15) for i in list1]

print(list2)

Enter salary78000
[66300.0]


In [ ]:
dict1={1:'Ajay',2:'Raju',3:'Prem'}
print(dict1)

{1: 'Raju', 3: 'Prem'}


In [ ]:
dict3 ={"Dept":"CSE","details":{"year":"II","sec":"D","Count":71}}
print(dict3["details"]["year"])
print(dict3["details"]["sec"])
print(dict3["details"]["Count"])

II
D
71


In [ ]:
idl=[2,3,1,4]
names=["rcb","Raju","virat","ajay"]
new_dict=dict(zip(idl,names))
print(new_dict)

{2: 'rcb', 3: 'Raju', 1: 'virat', 4: 'ajay'}


In [ ]:
import numpy as np
A=np.array([1,2,3,4])   #1d array
print(A.ndim)
print(A.shape)
B=np.array([[1,2],[3,4],[5,6]]) #elements in each row = columns
print(B.shape)
print(B.ndim)
print(B)
c=np.array([[[2,4],[4,6]],[[7,8],[7,9]]])
print(c.ndim)
print(c.shape)
print(c)

1
(4,)
(3, 2)
2
[[1 2]
 [3 4]
 [5 6]]
3
(2, 2, 2)
[[[2 4]
  [4 6]]

 [[7 8]
  [7 9]]]


In [ ]:
A=np.ones((1,2,4))
print(A)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
#print all the numbers divisible by 8 using arange
A =np.arange(0,1001,8)
print(A)


[   0    8   16   24   32   40   48   56   64   72   80   88   96  104
  112  120  128  136  144  152  160  168  176  184  192  200  208  216
  224  232  240  248  256  264  272  280  288  296  304  312  320  328
  336  344  352  360  368  376  384  392  400  408  416  424  432  440
  448  456  464  472  480  488  496  504  512  520  528  536  544  552
  560  568  576  584  592  600  608  616  624  632  640  648  656  664
  672  680  688  696  704  712  720  728  736  744  752  760  768  776
  784  792  800  808  816  824  832  840  848  856  864  872  880  888
  896  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#split in a range into n numbers having common differences
A=np.linspace(45,55,11)
print(A)

[45. 46. 47. 48. 49. 50. 51. 52. 53. 54. 55.]


In [1]:
a=('ajay','raj','prem')
b=(1,1.3,'ravi')
print(a+b)

('ajay', 'raj', 'prem', 1, 1.3, 'ravi')


In [2]:
a=('thor','loki')
b=('hulk','peter')
print(a*5)
print(b*3)

('thor', 'loki', 'thor', 'loki', 'thor', 'loki', 'thor', 'loki', 'thor', 'loki')
('hulk', 'peter', 'hulk', 'peter', 'hulk', 'peter')


In [3]:
t=(54,66,74,81,20,11,13)
print(max(t))

81


In [4]:
#removing element from tuple
t=('a','b','c','d')
l=list(t)
print(l)
l.remove('c')
t=tuple(l)
print(t)

['a', 'b', 'c', 'd']
('a', 'b', 'd')


In [5]:
#add element to tuple
t=('a','b','c','d')
l=list(t)
print(l)
l.append('e')
t=tuple(l)
print(t)

['a', 'b', 'c', 'd']
('a', 'b', 'c', 'd', 'e')


In [7]:
tuple1=tuple('MARVEL')
print('Tuple is :')
print(tuple1)

Tuple is :
('M', 'A', 'R', 'V', 'E', 'L')


In [8]:
l1=[1,2,3,4,5,6]
print('tuple is')
print(tuple(l1))

tuple is
(1, 2, 3, 4, 5, 6)


In [9]:
t=('blue','red','yellow')
print(t[0])

blue


In [11]:
t=('peter','parker','mj')
print(t[-1])
print(len(t))

mj
3


In [13]:
s={'data','analysis','python'}
s.remove('analysis')
print(s)

{'python', 'data'}


In [14]:
s={11,2,4,3}
print(type(s))

<class 'set'>


In [16]:
s={'iron','cobalt','nickel','silver'}
s.add('gold')
print(s)

{'nickel', 'gold', 'iron', 'cobalt', 'silver'}


In [17]:
s.remove('cobalt')
print(s)

{'nickel', 'gold', 'iron', 'silver'}


In [18]:
s.pop()
print(s)

{'gold', 'iron', 'silver'}


In [19]:
s.clear()
print(s)

set()


In [20]:
s1={'ajay','silver','asta'}
s2={'yami','feugoleon'}
s1.update(s2)
print(s1)

{'ajay', 'feugoleon', 'yami', 'silver', 'asta'}


In [21]:
s1={'asta','nero',222,'yuno'}
s1.discard('nero')
print(s1)

{'yuno', 'asta', 222}


In [22]:
s={1,2,3,4,5,6}
print(len(s))

6


In [23]:
s={'goku','vegeta','broly','jiren'}
s1={1,2,3,4}
s1.update(s)
print(s1)

{1, 2, 3, 4, 'jiren', 'vegeta', 'goku', 'broly'}


In [26]:
s={'goku','vegeta','broly','jiren'}
s.pop()
print(s)

{'goku', 'jiren', 'vegeta'}
