In [4]:
import numpy as np

In [ ]:
A=np.arange(1,13).reshape(6,2)
print(A)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
a=np.linspace(2,5,6).reshape(3,2)
print(a)

[[2.  2.6]
 [3.2 3.8]
 [4.4 5. ]]


In [ ]:
b=np.array([45,67,89,12,34,51,90,98]).reshape(2,2,2)
print(b)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


In [ ]:
#resize changes the shape of the original array
#reshape changes needs saving in another variable
b=np.array([45,67,89,12,34,51,90,98])
b.resize(2,2,2)
print(b)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


In [ ]:
a=np.array([55,77,41,94])       #list will throw an error while arrays iterate themselves
b=np.array([21,98,44,11])
print(a-b)

[ 34 -21  -3  83]


In [ ]:
a=np.array([5,12,18,45]).reshape(2,2)
b=np.array([7,16,74,36]).reshape(2,2)
print(a)
print(b)
c=a*b               #one on one multiplication
print(c)

[[ 5 12]
 [18 45]]
[[ 7 16]
 [74 36]]
[[ 923  512]
 [3456 1908]]


In [ ]:
a=np.array([5,12,18,45]).reshape(2,2)
b=np.array([7,16,74,36]).reshape(2,2)
print(a)
print(b)
c=a@b               #Matrix multiplication
print(c)

[[ 5 12]
 [18 45]]
[[ 7 16]
 [74 36]]
[[ 923  512]
 [3456 1908]]


In [ ]:
a=np.array([5,12,18,45]).reshape(2,2)
b=np.array([7,16,74,36]).reshape(2,2)
print(a)
print(b)              #Matrix multiplication
print(a.dot(b))

[[ 5 12]
 [18 45]]
[[ 7 16]
 [74 36]]
[[ 923  512]
 [3456 1908]]


In [ ]:
a=np.array([21,55,41,2,84,15,1.1])
print(a.max())
print("____________________")
print(a.min())

84.0
____________________
1.1


In [ ]:
a=np.array([5,12,18,45]).reshape(2,2)
print(a)
print("____________________")
print(a.max(axis=0))                    #axis=0 =>column
print("____________________")
print(a.max(axis=1))                    #axis=1 =>row

[[ 5 12]
 [18 45]]
____________________
[18 45]
____________________
[12 45]


In [ ]:
a=np.array([5,12,18,45]).reshape(2,2)
b=np.array([7,16,74,36]).reshape(2,2)

print(a)
print("____________________")
print(b)
print("____________________")
print("After vertically stacking arrays")
print(np.vstack((a,b)))


[[ 5 12]
 [18 45]]
____________________
[[ 7 16]
 [74 36]]
____________________
After vertically stacking arrays
[[ 5 12]
 [18 45]
 [ 7 16]
 [74 36]]


In [ ]:
a=np.array([5,12,18,45]).reshape(2,2)
b=np.array([7,16,74,36]).reshape(2,2)

print(a)
print("____________________")
print(b)
print("____________________")
print("After horizontally stacking arrays")
print(np.hstack((a,b)))


[[ 5 12]
 [18 45]]
____________________
[[ 7 16]
 [74 36]]
____________________
After horizontally stacking arrays
[[ 5 12  7 16]
 [18 45 74 36]]


In [ ]:
a=np.array([5,12,18,45]).reshape(2,2)
b=np.array([7,16,74,36]).reshape(2,2)

print(a)
print("____________________")
print(b)
print("____________________")
print("After vertically stacking arrays")
print(np.stack((a,b),axis=1))


[[ 5 12]
 [18 45]]
____________________
[[ 7 16]
 [74 36]]
____________________
After vertically stacking arrays
[[[ 5 12]
  [ 7 16]]

 [[18 45]
  [74 36]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)                            #no. of rows become no. of groups
print("after dstack")               #no. of
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#Spltting arrays
a=np.arange(18).reshape(3,6)
print(a)
print("after splitting")
np.hsplit(a,(1,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[ 0],
        [ 6],
        [12]]),
 array([[ 1,  2],
        [ 7,  8],
        [13, 14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]])]

In [ ]:
a=np.array([54,4,2,14,26,4,6456,64,645,4,6,4,8,46,7,6]).reshape(4,4)
print(a)
print(a.argmax())

[[  54    4    2   14]
 [  26    4 6456 6456]
 [6456    4    6    4]
 [   8   46    7    6]]
6


In [ ]:
a=np.array([54,47,28,14,26,41,57,64,94,45,67,49,83,46,76,65]).reshape(4,4)
print(a)
print(a.argmin())

[[54 47 28 14]
 [26 41 57 64]
 [94 45 67 49]
 [83 46 76 65]]
3


In [ ]:
a=np.array([54,47,28,14,26,41,57,64,94,45,67,49,83,46,76,65]).reshape(4,4)
print(a)
print(a.argmin(axis=1))

[[54 47 28 14]
 [26 41 57 64]
 [94 45 67 49]
 [83 46 76 65]]
[3 0 1 1]


# *Statistics*

In [ ]:
a=np.array([1,2,5,6,4,3])
print("Mean",np.mean(a))
print("Median",np.median(a))
print("Variance",np.var(a))
print("standard deviation",np.std(a))

Mean 3.5
Median 3.5
Variance 2.9166666666666665
standard deviation 1.707825127659933


In [ ]:
a=np.pi
print(a)

3.141592653589793


In [ ]:
np.rad2deg(a)

180.0

In [ ]:
a=np.array([np.pi/4,np.pi/3,np.pi/2])
print(a)
b=np.rad2deg(a)
print(b)

[0.78539816 1.04719755 1.57079633]
[45. 60. 90.]


In [ ]:
a=np.array([0,30,45,,60,90,135,180])
b=np.deg2rad(a)
print(b)

[0.52359878 0.78539816 1.57079633 2.35619449 3.14159265]


In [ ]:
a=np.array([0,30,45,60,90])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [ ]:
np.sin(90)

0.8939966636005579

In [ ]:
a=7
b=5
print(np.hypot(a,b))

8.602325267042627


In [5]:
a=np.array([94,9,45,46,49,4,68,38,6])
print(np.searchsorted(a,6))

0


Linear Algebra and U functions

In [6]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,24,41,17])
print(np.add(a,b))

[  6 127 146  36  76  32]


In [7]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,24,41,17])
print(np.subtract(a,b))

[  2  21 -18 -12  -6  -2]


In [8]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,24,41,17])
print(np.divide(a,b))

[2.         1.39622642 0.7804878  0.5        0.85365854 0.88235294]


In [9]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,24,41,17])
print(np.divmod(a,b))

(array([2, 1, 0, 0, 0, 0]), array([ 0, 21, 64, 12, 35, 15]))


In [11]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,24,41,17])
print(np.diff(b))

[ 51  29 -58  17 -24]


In [12]:
a=np.array([4,54,34,21,5,85])
print(np.sort(a))

[ 4  5 21 34 54 85]


In [13]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,64,12,77])
print(np.union1d(a,b))

[ 2  4 12 15 35 53 64 74 77 82]


In [14]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,64,12,77])
print(np.intersect1d(a,b))

[12 64]


In [15]:
a=np.array([4,74,64,12,35,15])
b=np.array([2,53,82,64,12,77])
print(np.setdiff1d(a,b))

[ 4 15 35 74]


Round

In [16]:
a1=np.trunc([3.544])
print(a1)

[3.]


In [18]:
a1=np.fix([3.5444])
print(a1)

[3.]


In [22]:
a1=np.around(3.544789,3)
print(a1)

3.545


In [20]:
a1=np.ceil([4.554])
print(a1)

[5.]


In [21]:
a1=np.floor([4.554])
print(a1)

[4.]


More Functions

In [24]:
a=np.array([5,4,2,6,8,7,3,9])
print(np.cumsum(a))

[ 5  9 11 17 25 32 35 44]


In [25]:
a=np.array([5,4,2,6,8,7,3,9])
print(np.cumprod(a))

[     5     20     40    240   1920  13440  40320 362880]


In [26]:
print(np.lcm(45,22))
print(np.gcd(22,89))

990
1


In [27]:
a=np.array([55,65,84])
print(np.lcm.reduce(a))

60060


In [28]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]
